<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Smart Mirror') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Styles -->
    <?php echo $this->headLink(['rel'  => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico',
    ])
        ->prependStylesheet($this->basePath('assets/css/style.css'))
        ->prependStylesheet($this->basePath('assets/css/animations.css'))
        ->prependStylesheet($this->basePath('assets/css/compliment.css'))
        ->prependStylesheet($this->basePath('assets/css/clock.css'))
        ->prependStylesheet($this->basePath('assets/css/weather.css'))
        ->prependStylesheet($this->basePath('assets/vendor/weather-icons/css/weather-icons.min.css'))
        ->prependStylesheet($this->basePath('assets/vendor/weather-icons/css/weather-icons-wind.min.css'));
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript(); ?>

</head>
<body>
<div class="globalContainer">
    <?php echo $this->content; ?>
</div>
<?php echo $this->inlineScript() ?>
<script type="text/javascript" src="<?php echo $this->basePath('assets/js/bundle.js'); ?>"></script>
</body>
</html>