<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Smart Mirror') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Styles -->
    <?php echo $this->headLink(['rel'  => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico',
    ])
        ->prependStylesheet($this->basePath('assets/css/style.css'))
        ->prependStylesheet($this->basePath('assets/vendor/bootstrap/dist/css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('assets/vendor/bootstrap/dist/css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('assets/vendor/bootstrap/dist/js/bootstrap.min.js'))
        ->prependFile($this->basePath('assets/vendor/jquery/dist/jquery.min.js')); ?>

</head>
<body>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; <?php echo date('Y') ?> by Steve Parker. All rights reserved.</p>
    </footer>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>